spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    name: dataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: false
